plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
}

def ENV = System.getenv()
version = "${ENV.GITHUB_RUN_NUMBER}" ? "${minecraft_version}.${mod_version}.${ENV.GITHUB_RUN_NUMBER}" : "${minecraft_version}.${mod_version}.nobuildnumber"
group = project.maven_group

base {
    archivesName = project.archives_base_name + "-forge"
}

// Mojang ships Java 25 to end users in 26.1+, so your mod should target Java 25.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    mappings channel: "${minecraft_mappings}", version: "${minecraft_version}"

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'examplemod'
        }

        register('client')

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', project.archives_base_name, '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
        implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    if(use_fct.equals("true")) {
        //runtimeOnly "curse.maven:fct-${fct_id}:${fct_file_id}"
        implementation "maven.modrinth:fusion-connected-textures:${fusion_version}-neoforge-mc${minecraft_version}"
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "antiblocksrechiseled",
                "Specification-Vendor"    : "manmaed",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "manmaed",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            forge_version: forge_version,
            version: version,
            fusion_version: fusion_version
    ]
    var replaceMCmeta = [
            fusion_version: fusion_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
    filesMatching(['pack.mcmeta']) {
        expand replaceMCmeta
    }
}

publishMods {
    dryRun = (providers.environmentVariable("CURSE_DEPLOY").getOrNull() || providers.environmentVariable("MODRINTH_DEPLOY").getOrNull()) == null
    file = jar.archiveFile
    modLoaders.add("forge")
    type = BETA
    changelog = file("./changelog.md").text
    displayName = "${mod_name} v${project.version} - Forge - ${minecraft_version}"
    curseforge {
        accessToken = providers.environmentVariable("CURSE_DEPLOY")
        projectId = project.curseforge_id
        javaVersions.add(JavaVersion.VERSION_25)
        minecraftVersions.add("${minecraft_version}")
        optional {
            slug = 'fusion-connected-textures'
        }
    }
    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_DEPLOY")
        projectId  = project.modrinth_id
        minecraftVersions.add("${minecraft_version}")
        optional {
            slug = 'fusion-connected-textures'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}