# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.157.0

modmuss_publish=2.2.0


# Mod Properties
maven_group = net.manmaed
archives_base_name = antiblocksrechiseled

#Mod Stuff
mod_name=AntiBlocksReChiseled
mod_version=1

#CurseForge Stuff
use_fct=false
fusion_version=1.2.11a

#Publishg Task
curseforge_id=715567
modrinth_id=uLWeFJiL

#Other Mods
modmenu_pid=308702
modmenu_fid=4159524
