
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL = "https://github.com/manmaed/AntiBlocksReChiseled/issues"
[[mods]]
modId="antiblocksrechiseled"
version="${file.jarVersion}"
displayName="AntiBlocksReChiseled"
updateJSONURL="https://raw.githubusercontent.com/manmaed/AntiBlocksReChiseled/main/update.json"
logoFile="abrc.logo.png"
credits="manmaed"
authors="manmaed"
description='''
Readds The AnitBlocks From Chsiel'''
