modLoader="javafml"
loaderVersion="[48,)"
license="All rights reserved"
issueTrackerURL = "https://github.com/manmaed/AntiBlocksReChiseled/issues"
[[mods]]
modId="antiblocksrechiseled"
version="${file.jarVersion}"
displayName="AntiBlocksReChiseled"
updateJSONURL="https://raw.githubusercontent.com/manmaed/AntiBlocksReChiseled/main/forge/update.json"
authors="manmaed"
logoFile="abrc.logo.png"
description='''Readds The AnitBlocks From Chsiel'''
[[dependencies.antiblocksrechiseled]]
modId="forge"
mandatory=true
versionRange="[48.1.0,)"
ordering="NONE"
side="BOTH"