modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL = "https://github.com/manmaed/AntiBlocksReChiseled/issues"
[[mods]]
modId="antiblocksrechiseled"
version="${version}"
displayName="AntiBlocksReChiseled"
updateJSONURL="https://raw.githubusercontent.com/manmaed/AntiBlocksReChiseled/main/neo/update.json"
authors="manmaed"
logoFile="abrc.logo.png"
description='''Readds The AnitBlocks From Chsiel'''
[[dependencies.antiblocksrechiseled]]
modId="neoforge"
required=true
versionRange="[21.3.0-beta,)"
ordering="NONE"
side="BOTH"