name: Feature Request
description: Submit your feature request here
title: "[Feature Request]: "
labels: [enhancement]
body:
  - type: textarea
    id: featDesc
    attributes:
      label: Feature Description
      description: |
        Describe your feature request in as much detail as possible
    validations:
      required: true
