package net.manmaed.antiblocksrechiseled.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.manmaed.antiblocksrechiseled.blocks.*;
import net.minecraft.core.HolderLookup;

import java.util.concurrent.CompletableFuture;

public class ModLootTablesProvider extends FabricBlockLootSubProvider {
    protected ModLootTablesProvider(FabricPackOutput packOutput, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(packOutput, registriesFuture);
    }
  /*  protected ModLootTablesProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }*/

    @Override
    public void generate() {
        dropSelf(ABRCBrightColors.BRIGHT_WHITE);
        dropSelf(ABRCBrightColors.BRIGHT_ORANGE);
        dropSelf(ABRCBrightColors.BRIGHT_MAGENTA);
        dropSelf(ABRCBrightColors.BRIGHT_YELLOW);
        dropSelf(ABRCBrightColors.BRIGHT_CYAN);
        dropSelf(ABRCBrightColors.BRIGHT_BLUE);
        dropSelf(ABRCBrightColors.BRIGHT_GREEN);
        dropSelf(ABRCBrightColors.BRIGHT_RED);
        dropSelf(ABRCBrightColors.BRIGHT_BLACK);
        dropSelf(ABRCBrightColors.BRIGHT_WHITE_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_ORANGE_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_MAGENTA_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_YELLOW_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_CYAN_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_BLUE_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_GREEN_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_RED_BORDER);
        dropSelf(ABRCBrightColors.BRIGHT_BLACK_BORDER);
        dropSelf(ABRCWoolColors.WOOL_WHITE);
        dropSelf(ABRCWoolColors.WOOL_ORANGE);
        dropSelf(ABRCWoolColors.WOOL_MAGENTA);
        dropSelf(ABRCWoolColors.WOOL_LIGHT_BLUE);
        dropSelf(ABRCWoolColors.WOOL_YELLOW);
        dropSelf(ABRCWoolColors.WOOL_LIME);
        dropSelf(ABRCWoolColors.WOOL_PINK);
        dropSelf(ABRCWoolColors.WOOL_GRAY);
        dropSelf(ABRCWoolColors.WOOL_LIGHT_GRAY);
        dropSelf(ABRCWoolColors.WOOL_CYAN);
        dropSelf(ABRCWoolColors.WOOL_PURPLE);
        dropSelf(ABRCWoolColors.WOOL_BLUE);
        dropSelf(ABRCWoolColors.WOOL_BROWN);
        dropSelf(ABRCWoolColors.WOOL_GREEN);
        dropSelf(ABRCWoolColors.WOOL_RED);
        dropSelf(ABRCWoolColors.WOOL_WHITE_BORDER);
        dropSelf(ABRCWoolColors.WOOL_ORANGE_BORDER);
        dropSelf(ABRCWoolColors.WOOL_MAGENTA_BORDER);
        dropSelf(ABRCWoolColors.WOOL_LIGHT_BLUE_BORDER);
        dropSelf(ABRCWoolColors.WOOL_YELLOW_BORDER);
        dropSelf(ABRCWoolColors.WOOL_LIME_BORDER);
        dropSelf(ABRCWoolColors.WOOL_PINK_BORDER);
        dropSelf(ABRCWoolColors.WOOL_GRAY_BORDER);
        dropSelf(ABRCWoolColors.WOOL_LIGHT_GRAY_BORDER);
        dropSelf(ABRCWoolColors.WOOL_CYAN_BORDER);
        dropSelf(ABRCWoolColors.WOOL_PURPLE_BORDER);
        dropSelf(ABRCWoolColors.WOOL_BLUE_BORDER);
        dropSelf(ABRCWoolColors.WOOL_BROWN_BORDER);
        dropSelf(ABRCWoolColors.WOOL_GREEN_BORDER);
        dropSelf(ABRCWoolColors.WOOL_RED_BORDER);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_WHITE);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_BLACK);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_ORANGE);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_MAGENTA);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_YELLOW);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_CYAN);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_BLUE);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_GREEN);
        dropSelf(ABRCSlabs.SLAB_BRIGHT_RED);
        dropSelf(ABRCSlabs.SLAB_WOOL_WHITE);
        dropSelf(ABRCSlabs.SLAB_WOOL_ORANGE);
        dropSelf(ABRCSlabs.SLAB_WOOL_MAGENTA);
        dropSelf(ABRCSlabs.SLAB_WOOL_LIGHT_BLUE);
        dropSelf(ABRCSlabs.SLAB_WOOL_YELLOW);
        dropSelf(ABRCSlabs.SLAB_WOOL_LIME);
        dropSelf(ABRCSlabs.SLAB_WOOL_PINK);
        dropSelf(ABRCSlabs.SLAB_WOOL_GRAY);
        dropSelf(ABRCSlabs.SLAB_WOOL_LIGHT_GRAY);
        dropSelf(ABRCSlabs.SLAB_WOOL_CYAN);
        dropSelf(ABRCSlabs.SLAB_WOOL_PURPLE);
        dropSelf(ABRCSlabs.SLAB_WOOL_BLUE);
        dropSelf(ABRCSlabs.SLAB_WOOL_BROWN);
        dropSelf(ABRCSlabs.SLAB_WOOL_GREEN);
        dropSelf(ABRCSlabs.SLAB_WOOL_RED);
        dropSelf(ABRCStairs.STAIR_BRIGHT_WHITE);
        dropSelf(ABRCStairs.STAIR_BRIGHT_BLACK);
        dropSelf(ABRCStairs.STAIR_BRIGHT_ORANGE);
        dropSelf(ABRCStairs.STAIR_BRIGHT_MAGENTA);
        dropSelf(ABRCStairs.STAIR_BRIGHT_YELLOW);
        dropSelf(ABRCStairs.STAIR_BRIGHT_CYAN);
        dropSelf(ABRCStairs.STAIR_BRIGHT_BLUE);
        dropSelf(ABRCStairs.STAIR_BRIGHT_GREEN);
        dropSelf(ABRCStairs.STAIR_BRIGHT_RED);
        dropSelf(ABRCStairs.STAIR_WOOL_WHITE);
        dropSelf(ABRCStairs.STAIR_WOOL_ORANGE);
        dropSelf(ABRCStairs.STAIR_WOOL_MAGENTA);
        dropSelf(ABRCStairs.STAIR_WOOL_LIGHT_BLUE);
        dropSelf(ABRCStairs.STAIR_WOOL_YELLOW);
        dropSelf(ABRCStairs.STAIR_WOOL_LIME);
        dropSelf(ABRCStairs.STAIR_WOOL_PINK);
        dropSelf(ABRCStairs.STAIR_WOOL_GRAY);
        dropSelf(ABRCStairs.STAIR_WOOL_LIGHT_GRAY);
        dropSelf(ABRCStairs.STAIR_WOOL_CYAN);
        dropSelf(ABRCStairs.STAIR_WOOL_PURPLE);
        dropSelf(ABRCStairs.STAIR_WOOL_BLUE);
        dropSelf(ABRCStairs.STAIR_WOOL_BROWN);
        dropSelf(ABRCStairs.STAIR_WOOL_GREEN);
        dropSelf(ABRCStairs.STAIR_WOOL_RED);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_WHITE);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_ORANGE);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_MAGENTA);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_YELLOW);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_CYAN);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_BLUE);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_GREEN);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_RED);
        dropSelf(ABRCButtons.BUTTON_BRIGHT_BLACK);
        dropSelf(ABRCButtons.BUTTON_WOOL_WHITE);
        dropSelf(ABRCButtons.BUTTON_WOOL_ORANGE);
        dropSelf(ABRCButtons.BUTTON_WOOL_MAGENTA);
        dropSelf(ABRCButtons.BUTTON_WOOL_LIGHT_BLUE);
        dropSelf(ABRCButtons.BUTTON_WOOL_YELLOW);
        dropSelf(ABRCButtons.BUTTON_WOOL_LIME);
        dropSelf(ABRCButtons.BUTTON_WOOL_PINK);
        dropSelf(ABRCButtons.BUTTON_WOOL_GRAY);
        dropSelf(ABRCButtons.BUTTON_WOOL_LIGHT_GRAY);
        dropSelf(ABRCButtons.BUTTON_WOOL_CYAN);
        dropSelf(ABRCButtons.BUTTON_WOOL_PURPLE);
        dropSelf(ABRCButtons.BUTTON_WOOL_BLUE);
        dropSelf(ABRCButtons.BUTTON_WOOL_BROWN);
        dropSelf(ABRCButtons.BUTTON_WOOL_GREEN);
        dropSelf(ABRCButtons.BUTTON_WOOL_RED);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_WHITE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_ORANGE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_MAGENTA);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_YELLOW);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_CYAN);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_BLUE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_GREEN);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_RED);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_BRIGHT_BLACK);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_WHITE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_ORANGE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_MAGENTA);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_LIGHT_BLUE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_YELLOW);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_LIME);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_PINK);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_GRAY);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_LIGHT_GRAY);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_CYAN);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_PURPLE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_BLUE);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_BROWN);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_GREEN);
        dropSelf(ABRCPressurePlates.PRESSURE_PLATE_WOOL_RED);
    }
}
