package net.manmaed.antiblocksrechiseled.datagen;

import net.manmaed.antiblocksrechiseled.AntiBlocksReChiseled;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.common.data.LanguageProvider;

public class ModLangProvider extends LanguageProvider {
    public ModLangProvider(DataGenerator gen) {
        super(gen, AntiBlocksReChiseled.MOD_ID, "en_us");
    }

    @Override
    protected void addTranslations() {

        /*add(ABRCStairs.STAIR_BLACK.get(), "");
        */
        //TODO: Implerment Auto Gen Lang Files
        /*
        BRIGHT_WHITE
BRIGHT_ORANGE
BRIGHT_MAGENTA
BRIGHT_YELLOW
BRIGHT_CYAN
BRIGHT_BLUE
BRIGHT_GREEN
BRIGHT_RED
BRIGHT_BLACK
BRIGHT_WHITE_BORDER
BRIGHT_ORANGE_BORDER
BRIGHT_MAGENTA_BORDER
BRIGHT_YELLOW_BORDER
BRIGHT_CYAN_BORDER
BRIGHT_BLUE_BORDER
BRIGHT_GREEN_BORDER
BRIGHT_RED_BORDER
BRIGHT_BLACK_BORDER
WOOL_WHITE
WOOL_ORANGE
WOOL_MAGENTA
WOOL_LIGHT_BLUE
WOOL_YELLOW
WOOL_LIME
WOOL_PINK
WOOL_GRAY
WOOL_LIGHT_GRAY
WOOL_CYAN
WOOL_PURPLE
WOOL_BLUE
WOOL_BROWN
WOOL_GREEN
WOOL_RED
WOOL_WHITE_BORDER
WOOL_ORANGE_BORDER
WOOL_MAGENTA_BORDER
WOOL_LIGHT_BLUE_BORDER
WOOL_YELLOW_BORDER
WOOL_LIME_BORDER
WOOL_PINK_BORDER
WOOL_GRAY_BORDER
WOOL_LIGHT_GRAY_BORDER
WOOL_CYAN_BORDER
WOOL_PURPLE_BORDER
WOOL_BLUE_BORDER
WOOL_BROWN_BORDER
WOOL_GREEN_BORDER
WOOL_RED_BORDER
SLAB_WHITE_BRIGHT
SLAB_BLACK
SLAB_ORANGE_BRIGHT
SLAB_MAGENTA_BRIGHT
SLAB_YELLOW_BRIGHT
SLAB_CYAN_BRIGHT
SLAB_BLUE_BRIGHT
SLAB_GREEN_BRIGHT
SLAB_RED_BRIGHT
SLAB_WHITE_WOOL
SLAB_ORANGE_WOOL
SLAB_MAGENTA_WOOL
SLAB_LIGHT_BLUE_WOOL
SLAB_YELLOW_WOOL
SLAB_LIME_WOOL
SLAB_PINK_WOOL
SLAB_GRAY_WOOL
SLAB_LIGHT_GRAY_WOOL
SLAB_CYAN_WOOL
SLAB_PURPLE_WOOL
SLAB_BLUE_WOOL
SLAB_BROWN_WOOL
SLAB_GREEN_WOOL
SLAB_RED_WOOL
STAIR_WHITE_BRIGHT
STAIR_BLACK
STAIR_ORANGE_BRIGHT
STAIR_MAGENTA_BRIGHT
STAIR_YELLOW_BRIGHT
STAIR_CYAN_BRIGHT
STAIR_BLUE_BRIGHT
STAIR_GREEN_BRIGHT
STAIR_RED_BRIGHT
STAIR_WHITE_WOOL
STAIR_ORANGE_WOOL
STAIR_MAGENTA_WOOL
STAIR_LIGHT_BLUE_WOOL
STAIR_YELLOW_WOOL
STAIR_LIME_WOOL
STAIR_PINK_WOOL
STAIR_GRAY_WOOL
STAIR_LIGHT_GRAY_WOOL
STAIR_CYAN_WOOL
STAIR_PURPLE_WOOL
STAIR_BLUE_WOOL
STAIR_BROWN_WOOL
STAIR_GREEN_WOOL
STAIR_RED_WOOL

         */


    }
}
